name: Test and Deploy

on:
  push:
    branches: [master]

jobs:
  Test:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: NexusPilot-Projects-Service-src

    steps:
      - uses: actions/checkout@v4
      - name: Setup .Net
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.x"
      - name: Install packages
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore
      - name: Test
        run: dotnet test --no-build --verbosity normal

  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.0.x"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image to Docker hub
        uses: docker/build-push-action@v5
        with:
          context: ./NexusPilot-Projects-Service-src
          file: ./NexusPilot-Projects-Service-src/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/nexuspilot-projects-service:latest
      - name: Install jq
        run: sudo apt-get install -y jq
      - name: Depoloy to Render
        run: |
          JSON_PAYLOAD=$(jq -n \
                         --arg image "$DOCKER_USERNAME/nexuspilot-projects-service:latest" \
                         '{image: $image}')
          curl -X PATCH \
            "https://api.render.com/v1/services/${{ secrets.RENDER_SERVICE_ID }}" \
            -H "Authorization: Bearer ${{ secrets.RENDER_API_KEY }}" \
            -H "Content-Type: application/json" \
            -d "$JSON_PAYLOAD"
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
